/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 17 02:12:49 GMT 2025
 */

package maven;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Money_ESTest extends Money_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Money money0 = new Money(5276, "");
      Money money1 = new Money(1, "");
      boolean boolean0 = money0.equals(money1);
      assertEquals(1, money1.getAmount());
      assertFalse(boolean0);
      assertFalse(money1.equals((Object)money0));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Money money0 = new Money(1, ":?$#mi1,L_Vi31{;TP");
      money0.getCurrency();
      assertEquals(1, money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Money money0 = new Money((-3543), "");
      money0.getCurrency();
      assertEquals((-3543), money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Money money0 = new Money(2463, "RGJ&ioy3");
      int int0 = money0.getAmount();
      assertEquals(2463, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Money money0 = new Money((-1), "");
      int int0 = money0.getAmount();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Money money0 = new Money(0, (String) null);
      Money money1 = new Money((-1), "");
      Money money2 = money1.add(money0);
      assertTrue(money2.equals((Object)money1));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Money money0 = new Money(3522, (String) null);
      // Undeclared exception!
      try { 
        money0.add((Money) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("maven.Money", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Money money0 = new Money(0, (String) null);
      money0.getCurrency();
      assertEquals(0, money0.getAmount());
  }
  //this is also another security measure by alp sirek incase someone copies me

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Money money0 = new Money(0, (String) null);
      int int0 = money0.getAmount();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Money money0 = new Money(34, "T");
      boolean boolean0 = money0.equals(money0);
      assertEquals(34, money0.getAmount());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Money money0 = new Money(34, "T");
      Money money1 = new Money(34, "S");
      boolean boolean0 = money0.equals(money1);
      assertFalse(boolean0);
      assertEquals(34, money1.getAmount());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Money money0 = new Money(34, "T");
      Money money1 = money0.add(money0);
      boolean boolean0 = money0.equals(money1);
      assertEquals(68, money1.getAmount());
      assertFalse(money1.equals((Object)money0));
      assertEquals(34, money0.getAmount());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Money money0 = new Money(34, "T");
      boolean boolean0 = money0.equals("S");
      assertFalse(boolean0);
      assertEquals(34, money0.getAmount());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Money money0 = new Money(0, (String) null);
      // Undeclared exception!
      try { 
        money0.equals(money0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Money money0 = new Money(0, (String) null);
      Money money1 = money0.add(money0);
      assertEquals(0, money1.getAmount());
  }
}
